### ISSUE TITLE
Issue on page /vast_database/overview/overview.html

### ISSUE THREAD

**Issue by thirstler** [vast-data/data-platform-field-docs#1]
The following:

"Data lake scale with full low-latency transaction capabilit Data warehouse-like performance Filtering on large amounts of data Simplicity: No sharding, HA is intrinsic to the system, no management of immutable obje"

looks like a cut-and-paste error of some sort.

**Comment by snowch** [comment]
Great catch - thanks, Jason!

**Comment by snowch** [comment]
Fixed.
